### ISSUE TITLE
Add rdfa

### ISSUE THREAD

**Issue by ktk** [zazuko/rdf-vocabularies#26]
http://www.w3.org/ns/rdfa#

And while we are at it, `vann`: http://vocab.org/vann/

**Comment by ktk** [comment]
I could not find vann in RDF so far.

**Comment by vhf** [comment]
Perhaps @iand could point us to the right place? :)

**Comment by iand** [comment]
The latest is at http://vocab.org/vann/vann-vocab-20100607.rdf

**Comment by vhf** [comment]
Unfortunately [`rdfxml-streaming-parser`](https://github.com/rdfjs/rdfxml-streaming-parser.js) cannot parse http://vocab.org/vann/vann-vocab-20100607.rdf because of this part:

```xml
  <cc:Work rdf:about="">
    <cc:license rdf:resource="http://creativecommons.org/licenses/by/1.0/"/>
    <dc:type rdf:resource="http://purl.org/dc/dcmitype/Text"/>
  </cc:Work>
```
which throws
```
ParseError: Invalid URI:
    at RdfXmlParser.newParseError (/rdf-vocabularies/node_modules/rdfxml-streaming-parser/lib/RdfXmlParser.js:140:16)
    at RdfXmlParser.uriToNamedNode (/rdf-vocabularies/node_modules/rdfxml-streaming-parser/lib/RdfXmlParser.js:165:24)
    at RdfXmlParser.valueToUri (/rdf-vocabularies/node_modules/rdfxml-streaming-parser/lib/RdfXmlParser.js:152:21)
    at RdfXmlParser.onTagResource (/rdf-vocabularies/node_modules/rdfxml-streaming-parser/lib/RdfXmlParser.js:334:73)
    at RdfXmlParser.onTag (/rdf-vocabularies/node_modules/rdfxml-streaming-parser/lib/RdfXmlParser.js:230:18)
    at SAXStream.emit (events.js:200:13)
    at SAXParser.me._parser.<computed> [as onopentag] (/rdf-vocabularies/node_modules/sax/lib/sax.js:258:17)
    at emit (/rdf-vocabularies/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/rdf-vocabularies/node_modules/sax/lib/sax.js:629:5)
    at openTag (/rdf-vocabularies/node_modules/sax/lib/sax.js:825:5)
```

<details><summary>(see test script)</summary>

```js
const fs = require('fs')
const RdfXmlParser = require('rdfxml-streaming-parser').RdfXmlParser
const myParser = new RdfXmlParser()

fs.createReadStream('./vann-vocab-20100607.rdf')
  .pipe(myParser)
  .on('data', console.log)
  .on('error', console.error)
  .on('end', () => console.log('All triples were parsed!'))
```
</details>

**Comment by ktk** [comment]
Ping @rubensworks, any ideas?

**Comment by rubensworks** [comment]
@vhf Can you try passing this to the constructor: `{ baseIRI: 'http://vocab.org/vann/vann-vocab-20100607.rdf ' }` ?

**Comment by vhf** [comment]
Sure, with the same test script as above and your suggestion I get a similar error:

```
ParseError: Invalid URI: http://vocab.org/vann/vann-vocab-20100607.rdf
    at RdfXmlParser.newParseError (/rdf-vocabularies/node_modules/rdfxml-streaming-parser/lib/RdfXmlParser.js:140:16)
    at RdfXmlParser.uriToNamedNode (/rdf-vocabularies/node_modules/rdfxml-streaming-parser/lib/RdfXmlParser.js:165:24)
    at RdfXmlParser.valueToUri (/rdf-vocabularies/node_modules/rdfxml-streaming-parser/lib/RdfXmlParser.js:152:21)
    at RdfXmlParser.onTagResource (/rdf-vocabularies/node_modules/rdfxml-streaming-parser/lib/RdfXmlParser.js:334:73)
    at RdfXmlParser.onTag (/rdf-vocabularies/node_modules/rdfxml-streaming-parser/lib/RdfXmlParser.js:230:18)
    at SAXStream.emit (events.js:200:13)
    at SAXParser.me._parser.<computed> [as onopentag] (/rdf-vocabularies/node_modules/sax/lib/sax.js:258:17)
    at emit (/rdf-vocabularies/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/rdf-vocabularies/node_modules/sax/lib/sax.js:629:5)
    at openTag (/rdf-vocabularies/node_modules/sax/lib/sax.js:825:5)
```

**Comment by vhf** [comment]
Sorry @rubensworks , I got it wrong and your suggestion does indeed solve the issue! 👍 

(You cannot see it above but it says that `http://vocab.org/vann/vann-vocab-20100607.rdf ` is not a valid URI (notice the space at the end of the string 🤦‍♂ )).

**Comment by rubensworks** [comment]
Ah ok, I was just about to say that it would probably be a forbidden character somewhere messing things up.
But good, it's working now :-)
